-- This is the default fallback language. Do NOT edit this file!
YAWS.Language.Languages['English'] = {
    icon = "flags16/gb.png",

    --
    -- Chat Messages
    --
    chat_no_permission = "You aren't allowed to do that.", -- They aren't allowed to perform a certain action.
    net_cooldown = "Your sending too many packets to the server, please wait and try again.", -- They're spamming the server with net messages.
    error = "Looks like something went wrong. Try again later.", -- uhhhhh shit.

    admin_permissions_saved = "Successfully saved your new permissions.", -- Confirmation that the new permissions have been saved.
    admin_config_saved = "Successfully saved your config.", -- Confirmation that the new config have been saved.

    admin_preset_added = "Successfully added a new preset.", -- Confirmation that a new preset has been added.
    admin_preset_edited = "Successfully edited preset.", -- Preset edited.
    admin_preset_nope = "Your preset is missing information.", -- Preset tried to be submitted without a name and/or reason.
    admin_preset_dupe = "A preset with that name already exists.", -- Preset tried to be submitted without a unique name.
    admin_preset_cantfind = "That preset can't be found.", -- Preset can't be found.
    admin_preset_removed = "Preset was removed.", -- Preset was removed.
    admin_preset_limit = "You can't have more than 32 presets.", -- Hitting the preset count limit.

    admin_player_warned = "Successfully warned %s.", -- Conformation to the admin that a player got warned.
    admin_player_note_update = "Successfully updated that players admin notes.", -- Conformation to the admin that a players notes got updated.
    admin_player_wipewarns = "Successfully wiped all warnings from %s.", -- Conformation to the admin that a players warnings got wiped.
    admin_player_joinwithactive = "%s has joined the server with %s active points.", -- Warning to admins that player joined with active points.

    admin_punishment_created = "Punishment created.", -- Conformation that a punishment got created
    admin_punishment_removed = "Punishment removed.", -- Conformation that a punishment got removed
    admin_punishment_edited = "Punishment edited.", -- Conformation that a punishment got edited
    
    player_warn_notice = "%s has issued a warn to you, for the following reason: %s", -- Message to the player they got warned.
    player_warn_broadcast = "%s has been warned by %s for the following reason: %s", -- Broadcast to everyone about a warning.
    player_warn_immune = "This player is immune from being warned.", -- Message to the player that they can't be warned.
    player_warn_noreason = "Please specify a reason to warn this player.", -- Tried to warn a player without a reason.
    player_warn_toolong = "Your reason cannot be longer than 150 characters.", -- Reason is too long.
    player_warn_maxpoints = "You can only put a maximum of %s points on a warn.", -- Tried to warn a player with more than the max points.
    player_warn_help = "To warn a player through the chat, use: !warn <player> <point count> <reason>", -- Help for warning in the chat
    player_warn_help_console = "To warn a player through the console, use: yaws warn <player> <point count> <reason>", -- Help for warning in the console
    player_warn_searchid_wait = "Searching... please wait...", -- Please wait for searching for a warn ID.
    player_warn_searchid_nonefound = "No warning with that ID was found.", -- Nothing found.
    player_warn_ui = "You cannot warn through the chat as you are only permitted to use presets.", -- Message to the player that they can't warn through the chat.
    player_warn_not_found = "Could not find player \"%s\".", -- Tried to warn a player through the chat that couldn't be found
    player_warn_wrongpoints = "The point count specified was invalid.", -- Tried to warn a player through the chat with an invalid point count.
    player_warn_notyou = "You can't warn yourself.", -- Tried to warn themselves.
    player_warn_deleted = "Successfully deleted warning.", -- Deleted warning.
    player_warn_deleted_user = "%s has deleted one of your warnings.", -- Deleted warning but it's the user.


    --
    -- UI
    --
    generic_save = "Save Changes", -- Used for any "save" buttons.
    generic_cancel = "Cancel", -- Used for any "cancel" buttons.
    generic_back = "Back", -- Used for any "back" buttons.
    generic_point_count = "Point Count", -- For the "point count" placeholders
    generic_delete = "Delete", -- Delete generic
    generic_warned = "WARNED", -- Warned - Used in the warnings cards
    
    -- Sidebar Tabs
    sidebar_warnings = "Warnings", -- Sidebar text for the warnings tab.
    sidebar_players = "Players", -- Sidebar text for the players tab.
    sidebar_admin = "Admin", -- Sidebar text for the admin tab.
    sidebar_settings = "Settings", -- Sidebar text for the settings tab.
    sidebar_close = "Close", -- Sidebar text for the close button.
    
    -- Players tab
    players_tab_search = "Search via name/steamid(64).", -- Text for the search box in the Players tab without online players.
    players_tab_search_button = "Submit Search", -- Text for the search button.
    players_tab_offline = "Search for offline players too?", -- Include offline players text. Careful of how big this is.
    
    viewing_player_no_warns_found = "There were no warnings found for this player.", -- Message when no warnings are found for a player.
    viewing_player_action_submit_warn = "Submit New Warning", -- Button for submitting a new warning.
    viewing_player_action_view_notes = "View Admin Notes", -- Button for viewing admin notes.
    viewing_player_player_notes = "Admin Notes", -- Admin Notes placeholder
    viewing_player_save_player_notes = "Save Admin Notes", -- Save the admin notes button

    viewing_player_table_admin = "Admin", -- Admin table header
    viewing_player_table_reason = "Reason", -- Reason table header
    viewing_player_table_time = "Time", -- Time table header
    viewing_player_table_points = "Points", -- Points table header
    viewing_player_table_server = "Server", -- Server table header

    viewing_player_table_right_id = "Copy Warning ID", -- Copy ID button
    viewing_player_table_right_admin = "Copy Admin", -- Copy admin button
    viewing_player_table_right_reason = "Copy Reason", -- Copy reason button
    viewing_player_table_right_time = "Copy Time", -- Copy time button
    viewing_player_table_right_points = "Copy Points Added", -- Copy points button
    viewing_player_table_right_server = "Copy Server Name", -- Copy server button
    viewing_player_table_right_log = "Copy as Log", -- Copy server button
    viewing_player_table_log_format = "[%s] %s(%s) warned %s(%s) for the reason \"%s\", adding %s points.", -- Log format. %s = timestamp, admin, steamid, player, steamid, reason and then point count.

    viewing_player_wipe_header = "Wipe all of %s's warnings?", -- Wipe a players warnings header
    viewing_player_wipe_subtext = "This is irreversible. Make sure this is what you want to do.", -- Wipe a players warnings subtext

    viewing_warn_time = "Time", -- Time header
    viewing_warn_point = "Point Penalty", -- Points header
    viewing_warn_server = "Server", -- Server header
    viewing_warn_reason = "Reason", -- Reason header

    -- Warning Players
    warn_player_submit = "Warn Player", -- Warn Player submit.
    warn_player_reason = "Reason for Warn", -- Reason for warn placeholder.

    -- Admin Tab
    admin_tab_sidebar_permissions = "Permissions", -- Sidebar text for the permissions tab. 
    admin_tab_sidebar_settings = "Settings", -- Sidebar text for the settings tab. 
    admin_tab_sidebar_presets = "Presets", -- Sidebar text for the presets tab. 
    admin_tab_sidebar_punishments = "Punishments", -- Sidebar text for the punishments tab. 
    admin_tab_sidebar_yaws = "YAWS", -- Sidebar text for the yaws tab. 
    
    admin_tab_presets_name = "Preset Name", -- Name in preset creation. 
    admin_tab_presets_reason = "Preset Reason", -- Reason in preset creation. 
    admin_tab_presets_create = "Create Preset", -- Create Preset button. 

    admin_tab_punishments_selecttype = "Select Punishment Type", -- Text in selecting a punishment type. 
    admin_tab_punishments_create = "Create Punishment Threshold", -- Text in selecting a punishment type. 
    admin_tab_punishments_notype = "No punishment type selected.", -- Default text for the descripton. 
    admin_tab_punishments_none = "There were no punishments found", -- Default text for the descripton. 
    -- admin_tab_punishments_edit_options = "Punishment Options", -- Punishment Options header. 

    admin_tab_warning_presets_box = "Select a Preset", -- Selecting a preset placeholder
    admin_tab_warning_reason_placeholder = "Enter a Reason", -- Enter a reason placeholder


    -- 
    -- Misc 
    -- 
    yaws_top = "This tab is only visible to the owner of the addon, a.k.a you", -- For the context menu and YAWS panel
    yaws = "Yet Another Warning System", -- For the context menu and YAWS panel
    yaws_version = "Release %s", -- Version
    yaws_outdated = "A new update is available. Please download it soon!", -- Version is outdated.

    context_warn = "Warn this Player", -- Warn Player button in the context menu
    context_presets = "Warn this Player using Presets", -- Warn Player button in the context menu w/ presets
    context_points = "Point Count: %s", -- Point Count viewing
    context_reason = "Warning Reason: %s", -- Reason viewing
    context_submit = "Submit Warning", -- Submit Warning
    context_viewwarns = "View Warnings", -- View Warnings
    context_viewnotes = "View Admin Notes", -- View Admin Notes

    page_format = "Page %s/%s", -- Page readout format

    no_player_found1 = "No players matching that filter were found.", -- No players were found line 1
    no_player_found2 = "Try a different filter.", -- No players were found line 2
    no_warning_found1 = "No warnings were found for this player.", -- No warnings were found line 1
    no_warning_found2 = "What an angel!", -- No warnings were found line 2
    no_punishment_found1 = "No punishments were found.", -- No punishments were found line 1
    no_punishment_found2 = "We'll leave it to your admins to do that!", -- No punishments were found line 2
    no_presets_found1 = "No presets were found.", -- No presets were found line 1
    no_presets_found2 = "We get it, you like to do things yourself.", -- No presets were found line 2

    points_format = "%s Point(s)", -- Points format for fancy UIs

    loading = "Loading...", -- Loading screen
    loading_hehe = "Playing Satisfactory...", -- aGVoZQ==

    accessability_points = "Active Points", -- accessability points text
    accessability_inactivepoints = "Inactive Points", -- accessability inactive points text

    -- Permission names
    permission_view_ui = "Open the UI",
    permission_view_self_warns = "View Their Own Warnings",
    permission_view_others_warns = "View Others Warnings",
    permission_view_admin_settings = "View and Edit Admin Settings",
    permission_create_warns = "Create Warnings",
    permission_customise_reason = "Use Custom Reasons",
    permission_delete_warns = "Delete Warnings",

    -- User settings names/descriptions
    user_settings_darkmode_name = "Dark Mode",
    user_settings_darkmode_desc = "Enable dark mode inside the UI.",

    user_settings_language_name = "Language",
    user_settings_language_desc = "Which langauge would you like to see the addon in? Requires reopening the UI.",

    user_settings_blur_name = "Blur Background",
    user_settings_blur_desc = "Enable bluring on the UI background. Requires reopening the UI.",

    user_settings_switchicons_name = "Enable Switch Icons",
    user_settings_switchicons_desc = "Enables tick/cross icons on switches for accessibility.",

    user_settings_colorblindtxt_name = "Enable Additional Texts",
    user_settings_colorblindtxt_desc = "Enables additional text for accessibility.",

    user_settings_tableview_name = "Table View",
    user_settings_tableview_desc = "Instead of viewing warning cards, view warnings as a table. For the most SERIOUS Warning Viewing Experience™",

    user_settings_disablefade_name = "Disable UI Fading",
    user_settings_disablefade_desc = "Disables the fade in/out of the main UI panel for that extra 5ms of speed!",

    user_settings_disableanim_name = "Disable UI Animations",
    user_settings_disableanim_desc = "Disables all internal UI animations.",
    
    -- Categories
    user_settings_category_interface = "User Interface",
    user_settings_category_accessibility = "Accessibility",

    -- Admin settings names/descriptions

    -- Branding
    admin_settings_prefix_name = "Prefix",
    admin_settings_prefix_desc = "The prefix the addon will use in chat messages.",

    admin_settings_prefix_color_name = "Prefix Color",
    admin_settings_prefix_color_desc = "The color of the prefix for chat messages.",

    admin_settings_chat_color_name = "Chat Color",
    admin_settings_chat_color_desc = "The color of the rest of all messages. Useful if your using a chatbox that doesn't work with white.",
    

    -- Warnings
    admin_settings_broadcast_warns_name = "Broadcast Warnings",
    admin_settings_broadcast_warns_desc = "If true, the addon will broadcast warnings to everyone online.",

    admin_settings_reason_required_name = "Reason Required?",
    admin_settings_reason_required_desc = "If true, admins will be required to put a reason for every warn.",

    admin_settings_purge_on_punishment_name = "Purge on Punishment",
    admin_settings_purge_on_punishment_desc = "If true, the addon will mark all a players points as inactive when they are punished.",


    -- Points
    admin_settings_point_cooldown_time_name = "Point Cooldown",
    admin_settings_point_cooldown_time_desc = "How long in seconds it takes for active points to be removed from a player. Set to 0 to disable this.",

    admin_settings_point_cooldown_amount_name = "Point Cooldown Amount",
    admin_settings_point_cooldown_amount_desc = "How many points to deduce each cooldown. Won't do anything if it's disabled.",

    admin_settings_point_max_name = "Maximum Points",
    admin_settings_point_max_desc = "The maximum amount of points one warn can have.",

    admin_settings_join_message_enabled_name = "Join Message Enabled",
    admin_settings_join_message_enabled_desc = "If true, the addon will send a message to players when they join with active points.",

    admin_settings_join_message_message_name = "Join Message",
    admin_settings_join_message_message_desc = "The message to send. {active} is active points, {inactive} is inactive points, {points} is total points", -- THIS IS TOO FUCKING LONG AAAA

    admin_settings_message_admins_on_active_join_name = "Message Admins after Player with Active Points Joins",
    admin_settings_message_admins_on_active_join_desc = "Send a warning to anyone with \"View Others Warnings\" permission when a player joins with active points.",

    -- The categories for the settings.
    admin_settings_category_points = "Points",
    admin_settings_category_branding = "Branding",
    admin_settings_category_warnings = "Warnings"
}