ITEM.name = "Mulched Leaves"
ITEM.model = "models/props_junk/garbage_bag001a.mdl"
ITEM.category = "Cocaine"
ITEM.desc = "A Bag of recently Mulched Leaves."
ITEM.noBusiness = true
ITEM.uniqueID = "mulchleaves"
ITEM.price = 0.36
ITEM.width = 2
ITEM.weight = 2