ENT.Type = "anim"
ENT.PrintName = "Jukebox"
ENT.Author = "Barata"
ENT.Contact = "Barata#8494"
ENT.Purpose = "Plays preset music in order."
ENT.Category = "Jukeboxes"
ENT.Instruction = "Interact with the Jukebox to skip the music."
ENT.Model = "models/fallout3/jukebox.mdl"
ENT.Spawnable = true
ENT.AdminSpawnable = true