ITEM.name = "Coca Seed"
ITEM.model = "models/comradebear/props/codww2/aac/cardboard_box_01.mdl"
ITEM.category = "Healthcure"
ITEM.desc = "A coca seed."
ITEM.noBusiness = true
ITEM.uniqueID = "cocaseed"
ITEM.price = 4.25
ITEM.width = 1
ITEM.height = 1