ITEM.name = "Poppy Seed"
ITEM.model = "models/comradebear/props/codww2/aac/cardboard_box_01.mdl"
ITEM.category = "Healthcure"
ITEM.desc = "A poppy seed."
ITEM.noBusiness = true
ITEM.uniqueID = "poppyseed"
ITEM.price = 4.25
ITEM.width = 1
ITEM.height = 1