ITEM.name = "Tomato Seed"
ITEM.model = "models/comradebear/props/codww2/aac/cardboard_box_01.mdl"
ITEM.category = "Healthcure"
ITEM.desc = "A tomato seed."
ITEM.noBusiness = true
ITEM.uniqueID = "tomatoseed"
ITEM.price = 4.25
ITEM.width = 1
ITEM.height = 1