SCHEMA.name = "External Gaming | 1942RP"
SCHEMA.author = "Lanius"
SCHEMA.desc = " 1942, Berlin"
nut.util.include("sv_database.lua")
nut.util.include("sh_configs.lua")
nut.util.include("sv_hooks.lua")
nut.util.include("cl_hooks.lua")
nut.util.include("sh_hooks.lua")
nut.util.include("meta/sh_player.lua")
nut.util.include("meta/sh_entity.lua")
nut.util.includeDir("libraries", nil, true)
-- Black Market Flag
nut.flag.add("v", "Access to the black market.")

-- Disables F1 menu when dead
if (SERVER) then
    hook.Add("PlayerDeath", "noF1OnDeath", function(ply)
        netstream.Start(ply, "removeF1")
    end)
else
    netstream.Hook("removeF1", function()
        if (IsValid(nut.gui.menu)) then
            nut.gui.menu:remove()
        end
    end)
end

--Charmusic
resource.AddFile("sound/charmusic2.mp3")


-- Disable picking up Vehicles
local function physgunPickup(client, ent)
    if ent:IsVehicle() and not client:IsAdmin() then return false end
end

hook.Add("PhysgunPickup", "no cars idot", physgunPickup)
--

-- Model Fix 

---CIVILIAN---
nut.anim.setModelClass("models/princeminusa/suits/male_08_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_08_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_08_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_08_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_09_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_09_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_09_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_09_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_07_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_07_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_07_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_07_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_06_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_06_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_06_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_06_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_05_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_05_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_05_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_05_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_04_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_04_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_04_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_04_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_03_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_03_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_03_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_03_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_02_closed_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_02_open.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_02_open_tie.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_02_open_waistcoat.mdl", "player")
nut.anim.setModelClass("models/princeminusa/suits/male_08_open_waistcoat.mdl", "player")

---NATIONALSOZIALISCHITE DEUTSCHE ARBEITERPARTEI---
nut.anim.setModelClass("models/not_brot/hitler/hitler.mdl", "player")
nut.anim.setModelClass("models/not_brot/fuhrer/hilter.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_candidate_01/reichsleitung_candidate_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_candidate_02/reichsleitung_candidate_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_candidate_03/reichsleitung_candidate_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_candidate_04/reichsleitung_candidate_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_candidate_05/reichsleitung_candidate_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_candidate_06/reichsleitung_candidate_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_01/reichsleitung_command_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_02/reichsleitung_command_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_03/reichsleitung_command_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_04/reichsleitung_command_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_05/reichsleitung_command_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_06/reichsleitung_command_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_summer_01/reichsleitung_command_summer_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_summer_02/reichsleitung_command_summer_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_summer_03/reichsleitung_command_summer_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_summer_04/reichsleitung_command_summer_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_summer_05/reichsleitung_command_summer_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_command_summer_06/reichsleitung_command_summer_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_01/reichsleitung_higher_administration_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_02/reichsleitung_higher_administration_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_03/reichsleitung_higher_administration_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_04/reichsleitung_higher_administration_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_05/reichsleitung_higher_administration_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_06/reichsleitung_higher_administration_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_summer_01/reichsleitung_higher_administration_summer_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_summer_02/reichsleitung_higher_administration_summer_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_summer_03/reichsleitung_higher_administration_summer_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_summer_04/reichsleitung_higher_administration_summer_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_summer_05/reichsleitung_higher_administration_summer_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_higher_admin_summer_06/reichsleitung_higher_administration_summer_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_01/reichsleitung_lower_administration_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_02/reichsleitung_lower_administration_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_03/reichsleitung_lower_administration_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_04/reichsleitung_lower_administration_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_05/reichsleitung_lower_administration_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_06/reichsleitung_lower_administration_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_summer_01/reichsleitung_lower_administration_summer_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_summer_02/reichsleitung_lower_administration_summer_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_summer_03/reichsleitung_lower_administration_summer_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_summer_04/reichsleitung_lower_administration_summer_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_summer_05/reichsleitung_lower_administration_summer_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/reichsleitung/reichs_lower_admin_summer_06/reichsleitung_lower_administration_summer_06.mdl", "player")

nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_candidate_01/gauleitung_candidate_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_candidate_02/gauleitung_candidate_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_candidate_03/gauleitung_candidate_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_candidate_04/gauleitung_candidate_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_candidate_05/gauleitung_candidate_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_candidate_06/gauleitung_candidate_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_command_01/gauleitung_command_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_command_02/gauleitung_command_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_command_03/gauleitung_command_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_command_04/gauleitung_command_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_command_05/gauleitung_command_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_command_06/gauleitung_command_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_higher_admin_01/gauleitung_higher_administration_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_higher_admin_02/gauleitung_higher_administration_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_higher_admin_03/gauleitung_higher_administration_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_higher_admin_04/gauleitung_higher_administration_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_higher_admin_05/gauleitung_higher_administration_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_higher_admin_06/gauleitung_higher_administration_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_lower_admin_01/gauleitung_lower_administration_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_lower_admin_02/gauleitung_lower_administration_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_lower_admin_03/gauleitung_lower_administration_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_lower_admin_04/gauleitung_lower_administration_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_lower_admin_05/gauleitung_lower_administration_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/gauleitung/gau_lower_admin_06/gauleitung_lower_administration_06.mdl", "player")

nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_candidate_01/kreisleitung_candidate_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_candidate_02/kreisleitung_candidate_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_candidate_03/kreisleitung_candidate_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_candidate_04/kreisleitung_candidate_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_candidate_05/kreisleitung_candidate_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_candidate_06/kreisleitung_candidate_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_command_01/kreisleitung_command_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_command_02/kreisleitung_command_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_command_03/kreisleitung_command_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_command_04/kreisleitung_command_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_command_05/kreisleitung_command_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_command_06/kreisleitung_command_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_higher_admin_01/kreisleitung_higher_administration_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_higher_admin_02/kreisleitung_higher_administration_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_higher_admin_03/kreisleitung_higher_administration_03mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_higher_admin_04/kreisleitung_higher_administration_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_higher_admin_05/kreisleitung_higher_administration_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_higher_admin_06/kreisleitung_higher_administration_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_lower_admin_01/kreisleitung_lower_administration_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_lower_admin_02/kreisleitung_lower_administration_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_lower_admin_03/kreisleitung_lower_administration_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_lower_admin_04/kreisleitung_lower_administration_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_lower_admin_05/kreisleitung_lower_administration_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/kreisleitung/kreis_lower_admin_06/kreisleitung_lower_administration_06.mdl", "player")

nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_candidate_01/ortsgruppenleitung_candidate_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_candidate_02/ortsgruppenleitung_candidate_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_candidate_03/ortsgruppenleitung_candidate_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_candidate_04/ortsgruppenleitung_candidate_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_candidate_05/ortsgruppenleitung_candidate_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_candidate_06/ortsgruppenleitung_candidate_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_command_01/ortsgruppenleitung_command_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_command_02/ortsgruppenleitung_command_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_command_03/ortsgruppenleitung_command_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_command_04/ortsgruppenleitung_command_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_command_05/ortsgruppenleitung_command_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_command_06/ortsgruppenleitung_command_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_lower_admin_01/ortsgruppenleitung_lower_administration_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_lower_admin_02/ortsgruppenleitung_lower_administration_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_lower_admin_03/ortsgruppenleitung_lower_administration_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_lower_admin_04/ortsgruppenleitung_lower_administration_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_lower_admin_05/ortsgruppenleitung_lower_administration_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_lower_admin_06/ortsgruppenleitung_lower_administration_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_operative_admin_01/ortsgruppenleitung_operative_administration_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_operative_admin_02/ortsgruppenleitung_operative_administration_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_operative_admin_03/ortsgruppenleitung_operative_administration_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_operative_admin_04/ortsgruppenleitung_operative_administration_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_operative_admin_05/ortsgruppenleitung_operative_administration_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/nsdap/ortsgruppenleitung/orts_operative_admin_06/ortsgruppenleitung_operative_administration_06.mdl", "player")

---SCHUTZSTAFFEL---
nut.anim.setModelClass("models/delos/ss_leather_coat/m37_s1_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/co1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/co2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/co3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/co4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/co5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/co6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/en1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/en2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/en3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/en4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/en5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/en6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/go1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/go2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/go3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/go4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/go5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/go6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/nco1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/nco2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/nco3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/nco4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/nco5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/1stssvt/nco6.mdl", "player")

nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/rf6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/co1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/co2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/co3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/co4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/co5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/co6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/en1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/en2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/en3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/en4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/en5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/en6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/go1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/go2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/go3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/go4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/go5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/go6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/nco1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/nco2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/nco3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/nco4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/nco5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/baseline/nco6.mdl", "player")

nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/co1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/co2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/co3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/co4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/co5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/co6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/en1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/en2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/en3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/en4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/en5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/en6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/go1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/go2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/go3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/go4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/go5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/go6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/nco1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/nco2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/nco3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/nco4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/nco5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/feld/nco6.mdl", "player")

nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/closecollargo6.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/infantry/co/m38_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/infantry/co/m42smock_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/infantry/en/m40_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/infantry/en/m40formal_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/infantry/en/m42smock_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/infantry/gen/m38_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/infantry/nco/m40_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/infantry/nco/m40formal_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/infantry/nco/m42smock_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/panzer/co/panzerwrap_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/panzer/en/panzeroveralls_s1_01.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/panzer/en/panzerwrap_s1_06.mdl", "player")
nut.anim.setModelClass("models/hts/comradebear/pm0v3/player/wssein/panzer/nco/panzerwrap_s1_06.mdl", "player")

nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/co1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/co2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/co3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/co4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/co5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/co6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/en1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/en2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/en3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/en4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/en5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/en6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/go1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/go2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/go3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/go4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/go5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/go6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/nco1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/nco2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/nco3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/nco4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/nco5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/ss/sd/nco6.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/sssuits/gspcoat1.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/sssuits/gspcoat2.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/sssuits/gspcoat3.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/sssuits/gspcoat4.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/sssuits/gspcoat5.mdl", "player")
nut.anim.setModelClass("models/not_brot/prometheus/sssuits/gspcoat6.mdl", "player")

nut.anim.setModelClass("models/not_brot/comradebear/pm0v3/ordnungspolizei/schutzpolizei/co/schutzpolizei_officer.mdl", "player")
nut.anim.setModelClass("models/not_brot/comradebear/pm0v3/ordnungspolizei/schutzpolizei/en/schutzpolizei_enlisted.mdl", "player")
nut.anim.setModelClass("models/not_brot/comradebear/pm0v3/ordnungspolizei/schutzpolizei/gen/schutzpolizei_general.mdl", "player")
nut.anim.setModelClass("models/not_brot/comradebear/pm0v3/ordnungspolizei/schutzpolizei/nco/schutzpolizei_nco.mdl", "player")
nut.anim.setModelClass("models/not_brot/comradebear/pm0v3/ordnungspolizei/schutzpolizei/snco/schutzpolizei_senior-nco.md", "player")

---STATE---
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg1_double_breasted_blue_01/deutsche_beamten_pay_group_1_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg1_double_breasted_blue_02/deutsche_beamten_pay_group_1_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg1_double_breasted_blue_03/deutsche_beamten_pay_group_1_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg1_double_breasted_blue_04/deutsche_beamten_pay_group_1_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg1_double_breasted_blue_05/deutsche_beamten_pay_group_1_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg1_double_breasted_blue_06/deutsche_beamten_pay_group_1_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg2_double_breasted_blue_01/deutsche_beamten_pay_group_2_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg2_double_breasted_blue_02/deutsche_beamten_pay_group_2_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg2_double_breasted_blue_03/deutsche_beamten_pay_group_2_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg2_double_breasted_blue_04/deutsche_beamten_pay_group_2_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg2_double_breasted_blue_05/deutsche_beamten_pay_group_2_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg2_double_breasted_blue_06/deutsche_beamten_pay_group_2_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg3_double_breasted_blue_01/deutsche_beamten_pay_group_3_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg3_double_breasted_blue_02/deutsche_beamten_pay_group_3_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg3_double_breasted_blue_03/deutsche_beamten_pay_group_3_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg3_double_breasted_blue_04/deutsche_beamten_pay_group_3_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg3_double_breasted_blue_05/deutsche_beamten_pay_group_3_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg3_double_breasted_blue_06/deutsche_beamten_pay_group_3_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg4_double_breasted_blue_01/deutsche_beamten_pay_group_4_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg4_double_breasted_blue_02/deutsche_beamten_pay_group_4_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg4_double_breasted_blue_03/deutsche_beamten_pay_group_4_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg4_double_breasted_blue_04/deutsche_beamten_pay_group_4_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg4_double_breasted_blue_05/deutsche_beamten_pay_group_4_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_blue/pg4_double_breasted_blue_06/deutsche_beamten_pay_group_4_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg1_double_breasted_grey_01/deutsche_beamten_pay_group_1_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg1_double_breasted_grey_02/deutsche_beamten_pay_group_1_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg1_double_breasted_grey_03/deutsche_beamten_pay_group_1_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg1_double_breasted_grey_04/deutsche_beamten_pay_group_1_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg1_double_breasted_grey_05/deutsche_beamten_pay_group_1_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg1_double_breasted_grey_06/deutsche_beamten_pay_group_1_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg2_double_breasted_grey_01/deutsche_beamten_pay_group_2_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg2_double_breasted_grey_02/deutsche_beamten_pay_group_2_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg2_double_breasted_grey_03/deutsche_beamten_pay_group_2_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg2_double_breasted_grey_04/deutsche_beamten_pay_group_2_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg2_double_breasted_grey_05/deutsche_beamten_pay_group_2_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg2_double_breasted_grey_06/deutsche_beamten_pay_group_2_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg3_double_breasted_grey_01/deutsche_beamten_pay_group_3_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg3_double_breasted_grey_02/deutsche_beamten_pay_group_3_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg3_double_breasted_grey_03/deutsche_beamten_pay_group_3_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg3_double_breasted_grey_04/deutsche_beamten_pay_group_3_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg3_double_breasted_grey_05/deutsche_beamten_pay_group_3_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg3_double_breasted_grey_06/deutsche_beamten_pay_group_3_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg4_double_breasted_grey_01/deutsche_beamten_pay_group_4_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg4_double_breasted_grey_02/deutsche_beamten_pay_group_4_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg4_double_breasted_grey_03/deutsche_beamten_pay_group_4_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg4_double_breasted_grey_04/deutsche_beamten_pay_group_4_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg4_double_breasted_grey_05/deutsche_beamten_pay_group_4_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/post_1940/double_breasted_grey/pg4_double_breasted_grey_06/deutsche_beamten_pay_group_4_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg1_double_breasted_blue_01/deutsche_beamten_pay_group_1_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg1_double_breasted_blue_02/deutsche_beamten_pay_group_1_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg1_double_breasted_blue_03/deutsche_beamten_pay_group_1_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg1_double_breasted_blue_04/deutsche_beamten_pay_group_1_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg1_double_breasted_blue_05/deutsche_beamten_pay_group_1_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg1_double_breasted_blue_06/deutsche_beamten_pay_group_1_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg2_double_breasted_blue_01/deutsche_beamten_pay_group_2_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg2_double_breasted_blue_02/deutsche_beamten_pay_group_2_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg2_double_breasted_blue_03/deutsche_beamten_pay_group_2_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg2_double_breasted_blue_04/deutsche_beamten_pay_group_2_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg2_double_breasted_blue_05/deutsche_beamten_pay_group_2_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg2_double_breasted_blue_06/deutsche_beamten_pay_group_2_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg3_double_breasted_blue_01/deutsche_beamten_pay_group_3_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg3_double_breasted_blue_02/deutsche_beamten_pay_group_3_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg3_double_breasted_blue_03/deutsche_beamten_pay_group_3_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg3_double_breasted_blue_04/deutsche_beamten_pay_group_3_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg3_double_breasted_blue_05/deutsche_beamten_pay_group_3_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg3_double_breasted_blue_06/deutsche_beamten_pay_group_3_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg4_double_breasted_blue_01/deutsche_beamten_pay_group_4_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg4_double_breasted_blue_02/deutsche_beamten_pay_group_4_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg4_double_breasted_blue_03/deutsche_beamten_pay_group_4_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg4_double_breasted_blue_04/deutsche_beamten_pay_group_4_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg4_double_breasted_blue_05/deutsche_beamten_pay_group_4_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_blue/pg4_double_breasted_blue_06/deutsche_beamten_pay_group_4_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg1_double_breasted_grey_01/deutsche_beamten_pay_group_1_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg1_double_breasted_grey_02/deutsche_beamten_pay_group_1_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg1_double_breasted_grey_03/deutsche_beamten_pay_group_1_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg1_double_breasted_grey_04/deutsche_beamten_pay_group_1_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg1_double_breasted_grey_05/deutsche_beamten_pay_group_1_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg1_double_breasted_grey_06/deutsche_beamten_pay_group_1_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg2_double_breasted_grey_01/deutsche_beamten_pay_group_2_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg2_double_breasted_grey_02/deutsche_beamten_pay_group_2_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg2_double_breasted_grey_03/deutsche_beamten_pay_group_2_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg2_double_breasted_grey_04/deutsche_beamten_pay_group_2_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg2_double_breasted_grey_05/deutsche_beamten_pay_group_2_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg2_double_breasted_grey_06/deutsche_beamten_pay_group_2_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg3_double_breasted_grey_01/deutsche_beamten_pay_group_3_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg3_double_breasted_grey_02/deutsche_beamten_pay_group_3_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg3_double_breasted_grey_03/deutsche_beamten_pay_group_3_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg3_double_breasted_grey_04/deutsche_beamten_pay_group_3_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg3_double_breasted_grey_05/deutsche_beamten_pay_group_3_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg3_double_breasted_grey_06/deutsche_beamten_pay_group_3_06.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg4_double_breasted_grey_01/deutsche_beamten_pay_group_4_01.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg4_double_breasted_grey_02/deutsche_beamten_pay_group_4_02.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg4_double_breasted_grey_03/deutsche_beamten_pay_group_4_03.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg4_double_breasted_grey_04/deutsche_beamten_pay_group_4_04.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg4_double_breasted_grey_05/deutsche_beamten_pay_group_4_05.mdl", "player")
nut.anim.setModelClass("models/not_brot/pm0v3/deutsche_beamten/pre_1940/double_breasted_grey/pg4_double_breasted_grey_06/deutsche_beamten_pay_group_4_06.mdl", "player")