ITEM.name = "Poppy"
ITEM.model = "models/gdrugs/cocaine/cocaine.mdl"
ITEM.category = "Healthcure"
ITEM.desc = "A Wet Brick Of Poppy Plants."
ITEM.noBusiness = true
ITEM.uniqueID = "poppy"
ITEM.price = 4.25
ITEM.width = 4
ITEM.height = 4